version: '3.1'

services:
  eshop-mysql:
    image: mysql
    restart: always
    container_name: "eshop-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - eshop-mysql-data:/var/lib/mysql

  eshop-redis:
    image: "redis:latest"
    container_name: "eshop-redis-container"
    ports:
      - "6379:6379"
    volumes:
      - eshop-redis-data:/data

volumes:
  eshop-redis-data:
  eshop-mysql-data:
